### ISSUE TITLE
Why do we include space, nb space and some control chars in extended subsets?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/nam-files#14]
These character are already covered in the non-extended subsets so I don't see the point in duplicating them?

**Comment by m4rc1e** [comment]
@garretrieger would you be opposed to me removing the following glyphs from every extended subset, https://github.com/googlefonts/nam-files/blob/main/Lib/gfsubsets/data/greek-ext_unique-glyphs.nam#L5-L8.

My issue is that `gftools add-font` will include the `greek-ext` subset for all families because our threshold for including an extended subset is only requiring 1% of characters. `greek-ext` only has 241 chars so 4/241=0.0165%. If I remove these glyphs, it won't trigger. If we can't remove these glyphs, I guess I could discount them from the set in `gftools add-font`.

**Comment by garretrieger** [comment]
Removing codepoints from a subset that have been included in pushed fonts can be risky, so if the only problem these are causing is with the tools then I'd prefer we try updating the tools first before resorting to subset changes.

**Comment by garretrieger** [comment]
I think it would be reasonable to just ignore those four characters for the purpose of subset selection as they occur frequently in various subsets and don't really signal any specific script.

**Comment by vv-monsalve** [comment]
> My issue is that `gftools add-font` will include the `greek-ext` subset for all families

I think this is also the case for `latin-ext` as it's [automatically added](https://github.com/google/fonts/blob/7177a071081e84e8a8faf278ec5a8d94d8585d42/ofl/playwritegbs/METADATA.pb#L25) in fonts that don't support it; and could also apply for `cyrillic-ext` see [gftools#829](https://github.com/googlefonts/gftools/issues/829)

**Comment by m4rc1e** [comment]
I'll make a fix for this today. Plan is to simply make the mod to the tools.
